name: PixelStacker
version: '1.1.2'
api-version: 1.21
author: Pangamma
#website: CustomPlugin
main: com.lumengaming.pixelstacker.PixelStackerMain
description: Generate photos with minecraft blocks.
depend: [WorldEdit]
commands:
  pixelstacker:
    description: 'Generate pixel art.'
    aliases: ['px', 'pixelartgenerator']