import fetch from "node-fetch";
import fs from 'fs';

const downloadFileAsync = (async (url, path) => {
    const res = await fetch(url);
    const fileStream = fs.createWriteStream(path);
    await new Promise((resolve, reject) => {
        res.body.pipe(fileStream);
        res.body.on("error", reject);
        fileStream.on("finish", resolve);
    });
});

async function build() {
    {
        const reply = await fetch('https://taylorlove.info/projects/pixelstacker/api/Definitions/MaterialList');
        const data = await reply.json();
        let content = `// --------------------------------------------------------
// DO NOT MODIFY THIS FILE.
// THIS FILE IS AUTOMATICALLY GENERATED.
// TO RE-GENERATE THIS FILE, RUN THIS CMD:
// npm run buildSprites
// --------------------------------------------------------

import { Material } from "./material";

function _(category: string, pixelStackerID: string, label: string, spriteX: number, spriteY: number, spritePage: number): Material {
    return {
        category,
        pixelStackerID,
        label,
        spriteX,
        spriteY,
        spritePage
    } as Material;
}
        
export const MaterialList: Material[] = [
    ${data.map(x => `_("${x.category}", "${x.pixelStackerID}", "${x.label}", ${x.spriteX}, ${x.spriteY}, ${x.spritePage})`).join(',\r\n    ')}
];`;

        fs.writeFileSync('src/models/materials.ts', content);

        const pages = data.map(x => x.spritePage).reduce((prev, cur) => {
            if (prev.indexOf(cur) === -1) { prev.push(cur); }
            return prev;
        }, []);

        for (let i = 0; i < pages.length; i++) {
            const [side, top] = [await downloadFileAsync(
                `https://taylorlove.info/projects/pixelstacker/api/Definitions/GetMaterialSpriteSheet?isSide=false&page=${pages[i]}`,
                `./public/img/top-sprite-${pages[i]}.png`),
            await downloadFileAsync(
                `https://taylorlove.info/projects/pixelstacker/api/Definitions/GetMaterialSpriteSheet?isSide=true&page=${pages[i]}`,
                `./public/img/side-sprite-${pages[i]}.png`)];
        }
    }
}

build();