//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelStacker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PixelStacker.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &apos;{0}&apos;.
        /// </summary>
        public static string Action_Add_0 {
            get {
                return ResourceManager.GetString("Action_Add_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Quantizer.
        /// </summary>
        public static string Action_DisableQuantizer {
            get {
                return ResourceManager.GetString("Action_DisableQuantizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Quantizer.
        /// </summary>
        public static string Action_EnableQuantizer {
            get {
                return ResourceManager.GetString("Action_EnableQuantizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Action_Filter {
            get {
                return ResourceManager.GetString("Action_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove &apos;{0}&apos;.
        /// </summary>
        public static string Action_Remove_0 {
            get {
                return ResourceManager.GetString("Action_Remove_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Action_Save {
            get {
                return ResourceManager.GetString("Action_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select profile.
        /// </summary>
        public static string DDL_SelectProfile {
            get {
                return ResourceManager.GetString("DDL_SelectProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one glass material must be enabled when you choose to require multiple layers..
        /// </summary>
        public static string Error_GlassRequiredForMultiLayer {
            get {
                return ResourceManager.GetString("Error_GlassRequiredForMultiLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough memory. Please try again or reduce image size if problem continues..
        /// </summary>
        public static string Error_NeedMoreRam {
            get {
                return ResourceManager.GetString("Error_NeedMoreRam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one non glass material must be selected..
        /// </summary>
        public static string Error_NonGlassRequired {
            get {
                return ResourceManager.GetString("Error_NonGlassRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one material must be enabled at all times..
        /// </summary>
        public static string Error_OneMaterialRequired {
            get {
                return ResourceManager.GetString("Error_OneMaterialRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something is wrong here..
        /// </summary>
        public static string Error_SomethingIsWrong {
            get {
                return ResourceManager.GetString("Error_SomethingIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Profile.
        /// </summary>
        public static string MaterialSelect_ColorProfile {
            get {
                return ResourceManager.GetString("MaterialSelect_ColorProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable 2nd Layer.
        /// </summary>
        public static string MaterialSelect_IsMultiLayer {
            get {
                return ResourceManager.GetString("MaterialSelect_IsMultiLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require 2nd Layer.
        /// </summary>
        public static string MaterialSelect_IsMultiLayerRequired {
            get {
                return ResourceManager.GetString("MaterialSelect_IsMultiLayerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side View.
        /// </summary>
        public static string MaterialSelect_IsSideView {
            get {
                return ResourceManager.GetString("MaterialSelect_IsSideView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Selection.
        /// </summary>
        public static string MaterialSelect_Title {
            get {
                return ResourceManager.GetString("MaterialSelect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset all PixelStacker options back to default settings? Includes materials, sizes, view states, rendering options, etc..
        /// </summary>
        public static string OtherOptions_ConfirmFactoryReset {
            get {
                return ResourceManager.GetString("OtherOptions_ConfirmFactoryReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Options.
        /// </summary>
        public static string OtherOptions_Title {
            get {
                return ResourceManager.GetString("OtherOptions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm.
        /// </summary>
        public static string PreRenderOptions_Algorithm {
            get {
                return ResourceManager.GetString("PreRenderOptions_Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different algorithms use different strategies for 
        ///combining colors together. Some use color buckets,
        ///others use locational distance to nearby colors. Try
        ///them all and decide which one is your favorite..
        /// </summary>
        public static string PreRenderOptions_Algorithm_Tooltip {
            get {
                return ResourceManager.GetString("PreRenderOptions_Algorithm_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Cache.
        /// </summary>
        public static string PreRenderOptions_ColorCache {
            get {
                return ResourceManager.GetString("PreRenderOptions_ColorCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Cache Size.
        /// </summary>
        public static string PreRenderOptions_ColorCacheSize {
            get {
                return ResourceManager.GetString("PreRenderOptions_ColorCacheSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smaller values are faster but less accurate.
        ///Higher values are slower but more accurate..
        /// </summary>
        public static string PreRenderOptions_ColorCacheSize_Tooltip {
            get {
                return ResourceManager.GetString("PreRenderOptions_ColorCacheSize_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Count.
        /// </summary>
        public static string PreRenderOptions_ColorCount {
            get {
                return ResourceManager.GetString("PreRenderOptions_ColorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max color count..
        /// </summary>
        public static string PreRenderOptions_ColorCount_Tooltip {
            get {
                return ResourceManager.GetString("PreRenderOptions_ColorCount_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dither.
        /// </summary>
        public static string PreRenderOptions_Dither {
            get {
                return ResourceManager.GetString("PreRenderOptions_Dither", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some people like dithering.
        ///I don&apos;t. I never do. I hate 
        ///dithering. But hey- you do you..
        /// </summary>
        public static string PreRenderOptions_Dither_Tooltip {
            get {
                return ResourceManager.GetString("PreRenderOptions_Dither_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel.
        /// </summary>
        public static string PreRenderOptions_Parallel {
            get {
                return ResourceManager.GetString("PreRenderOptions_Parallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed up the quantizing process by taking
        ///advantage of a multicore CPU. 
        ///
        ///Lower values = more stable
        ///Higher values = faster
        ///Super high values = possible glitches.
        /// </summary>
        public static string PreRenderOptions_Parallel_Tooltip {
            get {
                return ResourceManager.GetString("PreRenderOptions_Parallel_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuantizerSettings.
        /// </summary>
        public static string PreRenderOptions_QuantizerSettings {
            get {
                return ResourceManager.GetString("PreRenderOptions_QuantizerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling color map..
        /// </summary>
        public static string Progress_CompilingColorMap {
            get {
                return ResourceManager.GetString("Progress_CompilingColorMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished..
        /// </summary>
        public static string Progress_Finished {
            get {
                return ResourceManager.GetString("Progress_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing canvas for painting..
        /// </summary>
        public static string Progress_PreparingCanvasForTextures {
            get {
                return ResourceManager.GetString("Progress_PreparingCanvasForTextures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantizing Image.
        /// </summary>
        public static string Progress_QuantizingImage {
            get {
                return ResourceManager.GetString("Progress_QuantizingImage", resourceCulture);
            }
        }
    }
}
