<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <IsPackable>false</IsPackable>

    <UserSecretsId>52cf1f1d-7fd6-409b-8fd3-e10a40800f8e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentFTP" Version="54.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.9" />
    <PackageReference Include="OpenAI" Version="2.12.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.2.3" />
    <PackageReference Include="MSTest.TestFramework" Version="4.2.3" />
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SSH.NET" Version="2025.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PixelStacker.Logic\PixelStacker.Logic.csproj" />
  </ItemGroup>
</Project>
